version: '3.8'

services:
  app:
    image: plantpulse-server
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plantpulse
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    ports:
      - "8000:8000"

  mysql:
    image: mysql:5.7
    container_name: plantpulse_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: plantpulse
      MYSQL_USER:
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
