name: Deploy Laravel App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Install Docker
        run: |
          sudo yum update -y
          sudo amazon-linux-extras install docker
          sudo service docker start

      - name: Copy Files to EC2
        run: |
          scp -r -o StrictHostKeyChecking=no ./ ec2-user@ec2-3-28-123-21.me-central-1.compute.amazonaws.com:/var/www/html/plantpulse-backend

      - name: Run Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@ec2-3-28-123-21.me-central-1.compute.amazonaws.com "
            cd /var/www/html/plantpulse-backend &&
            docker-compose down &&
            docker-compose up -d --build
          "

